# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mycoldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_int', models.CharField(max_length=10)),
                ('user_col', models.CharField(max_length=10)),
            ],
        ),
    ]
